Add some missing death messages
Laskyyy/Create-Astral pull request #281
Opened 2024-03-05 21:45 UTC by edowski

i added death messages for throwing a spear at somebody and dying to the fusion reactor

2024-03-06 08:44 UTC, Erdragh approved these changes

2024-03-12 20:23 UTC, KonSola5 requested changes

2024-03-12 20:23 UTC, KonSola5 commented on kubejs/assets/tconstruct/lang/en_us.json
> +  "death.attack.fusion" : "%1$s expirienced radiance"
Typo: Should be "experienced".

2024-03-28 20:33 UTC, Loafin34 commented
what's traveler's backpack again?

2024-06-15 14:15 UTC, closed without merging

2024-06-15 14:15 UTC, Erdragh commented
Closing this as the changes will be merged via #313