Added incomplete (transitional) textures for a number of create sequence assemblies
Laskyyy/Create-Astral pull request #317
Opened 2024-06-18 20:58 UTC by mnorfolk03

I did not add the ae2 recipes, as they seem broken(?)

2024-06-19 03:42 UTC, mnorfolk03 commented
@Erdragh Can you take a look at this?

2024-06-20 10:11 UTC, Erdragh commented
I’ll take a look as soon as I can, but I’m rather busy on week days

2024-06-21 04:11 UTC, mnorfolk03 commented
I added some more textures for the incomplete (transitional) recipes, and added some textures for the t# upgrades. I didn't add t5, because it uses an integrated circuit, which may need a texture recolor, since it now uses a lead plate instead of the ad_astra plate. I can recolor it, & make the texture for the t5 upgrade if it needs to be done.

2024-06-27 11:05 UTC, Erdragh requested changes
Overall these changes are welcome, see the specific comments below for some minor things to change.

2024-06-27 11:05 UTC, Erdragh commented on kubejs/server_scripts/create.js
Please decide on a unified naming scheme for these helper variables (`inc_`, `incomplete_`, `transitional_`). This should probably be `incomplete_` as that's what's used in the localization.

2024-06-27 11:05 UTC, Erdragh commented on kubejs/server_scripts/server.js
Feel free to remove the things you commented out in the recipes here

2024-06-27 11:05 UTC, Erdragh commented on kubejs/server_scripts/server.js
Also feel free to move the create recipes in here into the create.js script

2024-06-27 11:05 UTC, Erdragh commented on resources/createastral/textures/item/crushed_raw_calorite.png
Where does this texture change come from? (Also applies to  the other crushed metals)

2024-06-27 11:58 UTC, Erdragh commented on kubejs/server_scripts/server.js
I've taken the freedom to do this

2024-06-27 11:58 UTC, Erdragh commented on kubejs/server_scripts/server.js
I've taken the freedom to do this

2024-06-27 11:58 UTC, Erdragh commented on kubejs/server_scripts/create.js
I've taken the freedom to do this

2024-06-27 12:00 UTC, Erdragh commented
> I can recolor it, & make the texture for the t5 upgrade if it needs to be done.
If you do this and justify the changes to the crushed metal textures I'll approve.

2024-06-27 16:19 UTC, mnorfolk03 commented on resources/createastral/textures/item/crushed_raw_calorite.png
I made it. They used to all be just recolors of crushed gold, so I changed them to differ since some of them looked pretty similar color-wise which confused me in game occasionally (I'm colorblind). We can change them back if you prefer though.

2024-06-27 16:21 UTC, mnorfolk03 commented
> > I can recolor it, & make the texture for the t5 upgrade if it needs to be done.
> 
> If you do this and justify the changes to the crushed metal textures I'll approve.


Finished those few textures, and wrote a comment about crushed metal textures. 

I also added transitional textures/models for the andesite casing => copper casing, and copper casing => tech reborn machine casing/frame

2024-06-27 16:35 UTC, Erdragh commented on resources/createastral/textures/item/crushed_raw_calorite.png
No that’s a perfectly valid reason. I’ll ask some other people (some also colorblind) what they think of the textures and then, after a re-review, it’s good to go

2024-06-27 18:50 UTC, Erdragh approved these changes
The changes overlapping between multiple PRs should be avoided next time. Other than that, thanks for your contribution!

2024-06-27 18:51 UTC, merged