Replaced all Plates with Sheets (closes #65)
Laskyyy/Create-Astral pull request #319
Opened 2024-06-25 18:55 UTC by mnorfolk03

Added sheet variants for all plates. Removed the rest of the unused plates from tech reborn, and removed ad astra iron plate

Following recipe changes:
  - nanosaber now uses carbon mesh instead of carbon sheet
  - tech reborn quarry fortune upgrade now uses lapis sheet instead of lazurite plate
  - iron ad astra sheet recipes replaced by create iron sheet
  - removed a few unused features that used some of the ad astra plates, like ad astra compressor

2024-06-25 18:55 UTC, mnorfolk03 commented
@Erdragh If you could also take a look at this when you get a chance!

2024-06-25 20:23 UTC, KonSola5 commented
@mnorfolk03, you might want to take a look at plates.js and replace the plates with sheets there too.

2024-06-25 21:40 UTC, mnorfolk03 commented
> @mnorfolk03, you might want to take a look at plates.js and replace the plates with sheets there too.

Done thanks! I also added tin there, since it is a sheet but doesn't have any use yet. I think we should try to give it some more, since it was not doing too much for me in my world besides tech reborn fluid cells & alloying with bronze. Maybe change some of the silver plates from TR recipes to tin plates? (for a future PR)

We also might want to think about getting rid of/or giving more recipes to invar & electrum, since they have like 2 recipes they're used for (electrum nuggets in the one sequenced assembly should be a pin probably)

2024-06-27 10:47 UTC, Erdragh requested changes
Some of the sheet textures, especially the ones for the Ad Astra plates, have very low contrast in my opinion. I would like them a lot more if they had darker borders, akin to the actual ingot textures.

2024-06-27 10:47 UTC, Erdragh commented on kubejs/server_scripts/removals.js
Why remove recipes for these items? Especially the engine frame? It makes it impossible to craft the desh rocket (Tier 2).

2024-06-27 10:47 UTC, Erdragh commented on kubejs/startup_scripts/startup.js
> +    // Transitional Items
These don't have textures yet, these seem to come with https://github.com/Laskyyy/Create-Astral/pull/317.

This means that that PR is a blocker for this one.

2024-06-27 12:06 UTC, Erdragh commented on kubejs/startup_scripts/startup.js
> +    // Transitional Items
I will merge #317 into this branch. This will require merging #317 before merging this.

2024-06-27 16:28 UTC, KonSola5 commented
An important thing:
Don't remove TR Wooden Plates, instead retexture them to resemble sheets.

That's because Wooden Plates are used to cover TR cables.

2024-06-27 17:30 UTC, mnorfolk03 commented on kubejs/server_scripts/removals.js
They are not used for anything. Engine frame was a mistake -- it should use sturdy sheet now instead of ad astral iron plate, like the engine fan did (before this pr)

2024-06-27 17:31 UTC, mnorfolk03 commented
> Some of the sheet textures, especially the ones for the Ad Astra plates, have very low contrast in my opinion. I would like them a lot more if they had darker borders, akin to the actual ingot textures.

Ad Astra sheets now better reflect their ingot textures. 



> An important thing: Don't remove TR Wooden Plates, instead retexture them to resemble sheets.
> 
> That's because Wooden Plates are used to cover TR cables.

Already taken care of, but thanks for checking!

2024-06-27 18:58 UTC, Erdragh approved these changes

2024-06-27 18:59 UTC, merged