Added fixes to tinkers construct recipes
Laskyyy/Create-Astral pull request #478
Opened 2024-12-19 22:00 UTC by mnorfolk03

Gold bars are now a cast that can be put into the cast chest once more
Shimmer now has proper tooltip
Netherite now has mixing recipe based on alloy smelter recipe

2024-12-19 22:50 UTC, TheRealGreenOxygen requested changes
Please remove the unheated recipe, because there is another way to get blazing blood earlier.
(Melting Blaze burners)

2024-12-21 23:50 UTC, mnorfolk03 commented
I don't think there's anything wrong with having multiple automation routes. This is a worse tier basically of the other blazing blood mixing recipe.

2025-01-04 10:55 UTC, TheRealGreenOxygen commented
It is not. 
A worse tier would required Heating, because the other one you are refereeing to requires superheating, this makes getting blazing blood bloody easy + Would make Blazing Blood possible before Moon access + would make getting Blazeburners possible before reaching moon, breaking progression.
Please delete that recipe.

2025-01-06 17:54 UTC, mnorfolk03 commented
> It is not. A worse tier would required Heating, because the other one you are refereeing to requires superheating, this makes getting blazing blood bloody easy + Would make Blazing Blood possible before Moon access + would make getting Blazeburners possible before reaching moon, breaking progression. Please delete that recipe.

You need blaze powder which requires blaze rods, which requires the moon, so I don't think it would break progression at all. I've changed it to require heating though good suggestion.

2025-04-15 17:21 UTC, merged